/* CVS $Id: AGGREGATOR.java,v 1.1 2007/05/12 07:41:26 rebach Exp $ */
package com.hp.hpl.jena.gvs.services.aggregator; 
import com.hp.hpl.jena.rdf.model.Model;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.Resource;
 
/**
 * Vocabulary definitions from /home/reto/workspace/gvs/rdf/aggregator.rdf 
 * @author Auto-generated by schemagen on 26 Oct 2006 15:13 
 */
public class AGGREGATOR {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://jena.hpl.hp.com/gvs/aggregator#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The time at which the attempt to download took place.</p> */
    public static final Property time = m_model.createProperty( "http://jena.hpl.hp.com/gvs/aggregator#time" );
    
    /** <p>The aggregator performing the DownloadAttempt.</p> */
    public static final Property aggregator = m_model.createProperty( "http://jena.hpl.hp.com/gvs/aggregator#aggregator" );
    
    /** <p>The source that was attempted to download.</p> */
    public static final Property aggregatedSource = m_model.createProperty( "http://jena.hpl.hp.com/gvs/aggregator#aggregatedSource" );
    
    /** <p>A text describing an error that occured during the download attempt described 
     *  by the subject.</p>
     */
    public static final Property warningMessage = m_model.createProperty( "http://jena.hpl.hp.com/gvs/aggregator#warningMessage" );
    
    /** <p>A text describing an error that occured during the download attempt described 
     *  by the subject.</p>
     */
    public static final Property errorMessage = m_model.createProperty( "http://jena.hpl.hp.com/gvs/aggregator#errorMessage" );
    
    /** <p>theamount of seconds between seconds</p> */
    public static final Property interval = m_model.createProperty( "http://jena.hpl.hp.com/gvs/aggregator#interval" );
    
    /** <p>Both succesfull and failed attempts.</p> */
    public static final Resource DownloadAttempt = m_model.createResource( "http://jena.hpl.hp.com/gvs/aggregator#DownloadAttempt" );
    
    /** <p>Typically a newsfeed.</p> */
    public static final Resource AggregatedSource = m_model.createResource( "http://jena.hpl.hp.com/gvs/aggregator#AggregatedSource" );
    
}
