/* CVS $Id: HTTPLISTENER.java,v 1.1 2007/05/12 07:41:44 rebach Exp $ */
package com.hp.hpl.jena.gvs.services; 
import com.hp.hpl.jena.rdf.model.Model;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.Resource;
 
/**
 * Vocabulary definitions from /home/reto/workspace/gvs/rdf/http-listener.rdf 
 * @author Auto-generated by schemagen on 08 Nov 2006 13:26 
 */
public class HTTPLISTENER {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://gvs.hpl.hp.com/ontologies/http-listener#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property port = m_model.createProperty( "http://gvs.hpl.hp.com/ontologies/http-listener#port" );
    
    public static final Property networkInterface = m_model.createProperty( "http://gvs.hpl.hp.com/ontologies/http-listener#networkInterface" );
    
}
