/* CVS $Id: SERVICES.java,v 1.1 2007/05/12 07:41:44 rebach Exp $ */
package com.hp.hpl.jena.gvs.services; 
import com.hp.hpl.jena.rdf.model.Model;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.Resource;
 
/**
 * Vocabulary definitions from /home/reto/workspace/gvs/rdf/services.rdf 
 * @author Auto-generated by schemagen on 08 Nov 2006 13:26 
 */
public class SERVICES {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://gvs.hpl.hp.com/ontologies/services#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>Typically a service takes its configuration from the trusted sources</p> */
    public static final Property trustedSource = m_model.createProperty( "http://gvs.hpl.hp.com/ontologies/services#trustedSource" );
    
    /** <p>This is the source that asserts the triples generated by the service</p> */
    public static final Property identity = m_model.createProperty( "http://gvs.hpl.hp.com/ontologies/services#identity" );
    
    /** <p>Points to a resource of which the description optained from the trusted sources 
     *  configures the service. Note that the object must be named so it can be passed 
     *  to the service.</p>
     */
    public static final Property configuration = m_model.createProperty( "http://gvs.hpl.hp.com/ontologies/services#configuration" );
    
    public static final Property factoryJavaClass = m_model.createProperty( "http://gvs.hpl.hp.com/ontologies/services#factoryJavaClass" );
    
    /** <p>the factoryJavaClass property point to an instance of com.hp.hpl.jena.gvs.services.ServiceFactory</p> */
    public static final Resource Service = m_model.createResource( "http://gvs.hpl.hp.com/ontologies/services#Service" );
    
}
