/* CVS $Id: ACCOUNTMANAGER.java,v 1.2 2007/05/01 09:57:27 rebach Exp $ */
package com.hp.hpl.jena.gvs.security; 
import com.hp.hpl.jena.rdf.model.Model;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.Resource;
 
/**
 * Vocabulary definitions from /home/reto/workspace/gvs/rdf/account-manager.rdf 
 * @author Auto-generated by schemagen on 12 Jan 2007 15:45 
 */
public class ACCOUNTMANAGER {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://gvs.hpl.hp.com/ontologies/account-manager#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property passwordSha1 = m_model.createProperty( "http://gvs.hpl.hp.com/ontologies/account-manager#passwordSha1" );
    
    public static final Property userName = m_model.createProperty( "http://gvs.hpl.hp.com/ontologies/account-manager#userName" );
    
}
