/* CVS $Id: METAMODEL.java,v 1.7 2007/05/15 13:54:13 rebach Exp $ */
package com.hp.hpl.jena.gvs.impl; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from /home/reto/workspace/gvs/rdf/metamodel.rdf 
 * @author Auto-generated by schemagen on 14 Mai 2007 14:34 
 */
public class METAMODEL {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://jena.hpl.hp.com/gvs/metamodel#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property describedIn = m_model.createProperty( "http://jena.hpl.hp.com/gvs/metamodel#describedIn" );
    
    /** <p>a strong hash of the subject</p> */
    public static final Property strongHashCode = m_model.createProperty( "http://jena.hpl.hp.com/gvs/metamodel#strongHashCode" );
    
    /** <p>a weak hash of the subject</p> */
    public static final Property hashCode = m_model.createProperty( "http://jena.hpl.hp.com/gvs/metamodel#hashCode" );
    
    /** <p>The graph asserted with an assertion</p> */
    public static final Property assertedComponent = m_model.createProperty( "http://jena.hpl.hp.com/gvs/metamodel#assertedComponent" );
    
    /** <p>the moment at which an assertion was made</p> */
    public static final Property revocationTime = m_model.createProperty( "http://jena.hpl.hp.com/gvs/metamodel#revocationTime" );
    
    /** <p>the moment at which an assertion was made</p> */
    public static final Property assertionTime = m_model.createProperty( "http://jena.hpl.hp.com/gvs/metamodel#assertionTime" );
    
    public static final Property containsNonTerminalMolecule = m_model.createProperty( "http://jena.hpl.hp.com/gvs/metamodel#containsNonTerminalMolecule" );
    
    public static final Property asserter = m_model.createProperty( "http://jena.hpl.hp.com/gvs/metamodel#asserter" );
    
    public static final Resource FunctionallyGroundedNode = m_model.createResource( "http://jena.hpl.hp.com/gvs/metamodel#FunctionallyGroundedNode" );
    
    public static final Resource ContextualMolecule = m_model.createResource( "http://jena.hpl.hp.com/gvs/metamodel#ContextualMolecule" );
    
    public static final Resource NonTerminalMolecule = m_model.createResource( "http://jena.hpl.hp.com/gvs/metamodel#NonTerminalMolecule" );
    
    public static final Resource TerminalMolecule = m_model.createResource( "http://jena.hpl.hp.com/gvs/metamodel#TerminalMolecule" );
    
    /** <p>Typically an agent or a newsfeed.</p> */
    public static final Resource Source = m_model.createResource( "http://jena.hpl.hp.com/gvs/metamodel#Source" );
    
    public static final Resource Graph = m_model.createResource( "http://jena.hpl.hp.com/gvs/metamodel#Graph" );
    
    /** <p>Cardinality of one for startTime and endTime, this doesn't prevent unrevoked 
     *  assertion not to have a known endDate. They will have eventually. Cardinality 
     *  1 for assertedComponent</p>
     */
    public static final Resource Assertion = m_model.createResource( "http://jena.hpl.hp.com/gvs/metamodel#Assertion" );
    
}
