/* CVS $Id: WEBACCOUNTMANAGER.java,v 1.1 2007/05/12 07:40:38 rebach Exp $ */
package com.hp.hpl.jena.gvs.services.http.accountmanager; 
import com.hp.hpl.jena.rdf.model.Model;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.Resource;
 
/**
 * Vocabulary definitions from /home/reto/workspace/gvs/rdf/web-account-manager.rdf 
 * @author Auto-generated by schemagen on 27 Dec 2006 22:08 
 */
public class WEBACCOUNTMANAGER {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://gvs.hpl.hp.com/ontologies/web-account-manager#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property fromAddress = m_model.createProperty( "http://gvs.hpl.hp.com/ontologies/web-account-manager#fromAddress" );
    
    public static final Property smtpServer = m_model.createProperty( "http://gvs.hpl.hp.com/ontologies/web-account-manager#smtpServer" );
    
    public static final Property webAccountManagerConfiguration = m_model.createProperty( "http://gvs.hpl.hp.com/ontologies/web-account-manager#webAccountManagerConfiguration" );
    
    public static final Resource WebAccountManagerConfiguration = m_model.createResource( "http://gvs.hpl.hp.com/ontologies/web-account-manager#WebAccountManagerConfiguration" );
    
}
